apiVersion: v1
kind: Service
metadata:
  name: projeto-exemplo-svc
spec:
  selector:
    app: projeto-exemplo
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-exemplo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projeto-exemplo
  template:
    metadata:
      labels:
        app: projeto-exemplo
    spec:
      containers:
      - name: projeto-exemplo
        image: brianmorais/projetoexemplonode:latest
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "production"
          - name: VIA_CEP_URL
            value: "https://viacep.com.br/ws/{CEP}/json"
          - name: PORT
            value: "3000"
