name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: moraisbrian/projetoexemplonode

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch

    - name: Build Docker Image
      run: docker build -t $DOCKER_IMAGE_NAME:${{ steps.version.outputs.version }} .

    - name: Push Docker Image
      run: |
        docker push $DOCKER_IMAGE_NAME:${{ steps.version.outputs.version }}
        docker tag $DOCKER_IMAGE_NAME:${{ steps.version.outputs.version }} $DOCKER_IMAGE_NAME:latest
        docker push $DOCKER_IMAGE_NAME:latest
